### ISSUE TITLE
Telegram API error: [400]

### ISSUE THREAD

**Issue by stepanovandrey89** [swap-dev/cryptonote-swap-pool#3] opened 2019-08-15 07:18 UTC
Hello! Tell me please how I can resolve problem: "Bad Request: chat not found" ?
Now notifications only come from the bot, but messages do not come to the group. Thanks.

**Comment by LPHuynh** [comment] 2019-08-15 14:02
I need more info and logs, but it sounds like a problem with your telegram bot setup, not a bug with the pool software.

**Comment by stepanovandrey89** [comment] 2019-08-17 19:12
Hello! 
pool/config.json

    "telegram": {
        "enabled": true,
        "botName": "@s********_bot",
        "token": "75******:AAG*******",
        "channel": "-10014205*****",

pool/logs# tail -f telegram_error.log
2019-08-17 19:46:27 Telegram API error: [400] Bad Request: chat not found
2019-08-17 20:01:53 Telegram API error: [400] Bad Request: chat not found

Sending a message to the group is successful by command:

/usr/bin/curl -F "chat_id=-10014205*****" -F "text=subject message" -X POST https://api.telegram.org/bot75******:AAG*******/sendMessage

Now only work private messages from the bot, when you try to send messages to the group out error. I understand that I myself made a mistake somewhere and ask for help to understand.

**Comment by stepanovandrey89** [comment] 2019-08-17 20:11
I'm sorry for the inconsideration. I was supposed to specify the name of the chat, not the group.

**Comment by LPHuynh** [comment] 2019-08-17 21:14
no problem. I'm closing this issue if it's solved.

**Closed as completed by LPHuynh** 2019-08-17 21:14 UTC
